import { upsertGoal, upsertHolding, upsertTransaction } from "./db";
import type { HoldingRow } from "./types";

const now = "2024-01-15T00:00:00.000Z";

function sampleHolding(partial: Partial<HoldingRow> & Pick<HoldingRow, "id" | "assetClass" | "name">): HoldingRow {
  return {
    subtype: "",
    ticker: "",
    exchange: "",
    sector: "",
    institution: "",
    accountRef: "",
    currency: "INR",
    fxRate: "1",
    quantity: "0",
    avgCost: "0",
    currentPrice: "",
    priceSource: "manual",
    priceUpdatedAt: "",
    manualValue: "",
    interestRate: "",
    compounding: "quarterly",
    payoutType: "cumulative",
    startDate: "",
    maturityDate: "",
    purchaseDate: "",
    maturityAmount: "",
    accruedInterest: "",
    sipAmount: "",
    sipFrequency: "",
    sipStart: "",
    employeeContribution: "",
    employerContribution: "",
    contributionFrequency: "",
    rentalIncome: "",
    monthlyCost: "",
    outstandingLoan: "",
    renewalStatus: "active",
    mfCategory: "",
    isEstimate: false,
    isSample: true,
    personalUse: false,
    countsAsInvestment: partial.assetClass !== "savings" && partial.assetClass !== "liability",
    notes: "SAMPLE — demonstration record, not your portfolio.",
    createdAt: now,
    updatedAt: now,
    ...partial,
  };
}

export function insertSample() {
  upsertHolding(
    sampleHolding({
      id: "sample-equity",
      assetClass: "equity",
      subtype: "stock",
      name: "Sample — Example Industries",
      ticker: "SAMPLE",
      exchange: "NSE",
      sector: "Demonstration",
      quantity: "0",
      currentPrice: "160",
      priceSource: "manual",
    }),
  );
  upsertTransaction({
    id: "sample-buy-1",
    holdingId: "sample-equity",
    type: "opening",
    date: "2023-01-10",
    quantity: "10",
    price: "100",
    amount: "1000",
    fees: "0",
    category: "Stock purchase",
    cashflowKind: "investment",
    currency: "INR",
    notes: "SAMPLE purchase",
    createdAt: now,
  });
  upsertTransaction({
    id: "sample-buy-2",
    holdingId: "sample-equity",
    type: "buy",
    date: "2023-06-10",
    quantity: "10",
    price: "200",
    amount: "2000",
    fees: "0",
    category: "Stock purchase",
    cashflowKind: "investment",
    currency: "INR",
    notes: "SAMPLE purchase",
    createdAt: now,
  });
  upsertTransaction({
    id: "sample-div",
    holdingId: "sample-equity",
    type: "dividend",
    date: "2024-03-01",
    quantity: "0",
    price: "0",
    amount: "80",
    fees: "0",
    category: "Dividend",
    cashflowKind: "income",
    currency: "INR",
    notes: "SAMPLE dividend",
    createdAt: now,
  });
  upsertHolding(
    sampleHolding({
      id: "sample-fd",
      assetClass: "fd",
      subtype: "fd",
      name: "Sample — Bank deposit",
      institution: "Sample Bank",
      avgCost: "100000",
      interestRate: "7.1",
      compounding: "quarterly",
      payoutType: "cumulative",
      startDate: "2024-01-01",
      maturityDate: "2025-01-01",
      renewalStatus: "active",
      notes: "SAMPLE — projected interest is an estimate, not a bank statement.",
    }),
  );
  upsertHolding(
    sampleHolding({
      id: "sample-cash",
      assetClass: "savings",
      subtype: "savings",
      name: "Sample — Savings account",
      institution: "Sample Bank",
      manualValue: "75000",
      countsAsInvestment: false,
    }),
  );
  upsertHolding(
    sampleHolding({
      id: "sample-loan",
      assetClass: "liability",
      subtype: "personal_loan",
      name: "Sample — Personal loan",
      institution: "Sample Bank",
      manualValue: "20000",
      countsAsInvestment: false,
      interestRate: "11",
    }),
  );
  upsertTransaction({
    id: "sample-salary",
    holdingId: null,
    type: "income",
    date: "2024-05-01",
    quantity: "0",
    price: "0",
    amount: "80000",
    fees: "0",
    category: "Salary",
    cashflowKind: "income",
    currency: "INR",
    notes: "SAMPLE salary",
    createdAt: now,
  });
  upsertTransaction({
    id: "sample-rent-exp",
    holdingId: null,
    type: "expense",
    date: "2024-05-02",
    quantity: "0",
    price: "0",
    amount: "25000",
    fees: "0",
    category: "Household",
    cashflowKind: "expense",
    currency: "INR",
    notes: "SAMPLE expense",
    createdAt: now,
  });
  upsertGoal({
    id: "sample-goal",
    name: "Sample — Emergency fund",
    targetAmount: "300000",
    targetDate: "2026-12-31",
    monthlyContribution: "10000",
    notes: "SAMPLE goal",
    isSample: true,
    createdAt: now,
    updatedAt: now,
  });
}
